server:
  port: 8081

social:
  service:
    url: http://localhost:8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pump_auth
    username: ${DB_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com.johnmartin.auth: TRACE