server:
  port: 8080
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s

  # Email
  # Disable Mail Health Indicator
  management:
    health:
      mail:
        enabled: false

# Services
external-services:
  social:
    url: http://pump-social-service:8080

# Logging
logging:
  level:
    org.springframework.boot.context.config: DEBUG
