spring.application.name=pump-auth-service
server.port=8081
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{requestId}] %-5level [%thread] %logger{36} - %msg%n

